# Generated by Django 4.1.1 on 2022-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Por favor, ingrese un valido correo.', 'required': 'Por favor este campo es requerido.', 'unique': 'Un usuario con este correo, ya existe.'}, max_length=254, unique=True, verbose_name='Correo'),
        ),
    ]
